### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by amenolo** [JoeBiellik/localdns#6]
Cool project, I just find a couple of features possibly missing:

1) admin dashboard, which could let you easily manage accounts/subdomains (e.g. in case of misconducts, complaints and so on)
2) account (or just subdomain at least) deletion option for users

Since are kind of basilar things, I guess you had your own good reasons for not to had those embed already, I tried to ask for it anyway :-)

Thanks
greetings

ps. 3. multi domains support, maybe...? Well, it thereupon wouldn't be tiny & simple anymore, I know...

**Comment by JoeBiellik** [comment]
Thanks for the suggestions, I've [implemented account deletion](https://github.com/JoeBiellik/localdns/commit/d39b7513056ac0d7fb23597828cd6011fb2278fb) in the [latest version](https://github.com/JoeBiellik/localdns/releases/tag/1.3.0).

An admin dashboard might be useful but would probably end up being more code the everything else so far. Considering how simple the database structure is I think its best to use a separate MongoDB tool for administration.

Multiple domain support wouldn't be too hard, I'd happily accept a PR if you wanted to implement it, otherwise, I will probably add it at some point.
